vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("v", "<C-c>", '"+y')
vim.keymap.set("n", "Q", "<Nop>")
vim.keymap.set("v", "<Leader>y", '"+y')

vim.keymap.set("n", "<Leader>tm", "lua ToggleMouse()")
vim.keymap.set({ "n" }, "<F8>", ":w | lua ShowOutput({compiler='python3'})<CR>")
vim.keymap.set({ "i" }, "<F8>", "<Esc>:w | lua ShowCodeOutput({compiler='python3'})<CR>")
vim.keymap.set({ "n" }, "<Leader>lcd", ":lcd %:p:h | pwd<CR>")
vim.keymap.set({ "n" }, "<Leader>tcd", ":tcd %:p:h | pwd<CR>")
vim.keymap.set({ "n" }, "<Leader>cd", ":cd %:p:h | pwd<CR>")
vim.keymap.set({ "n" }, "<Leader>R", ":restart<CR>")
vim.keymap.set({ "n" }, "<Leader>da", ":lua vim.diagnostic.setqflist()<CR>")
vim.keymap.set({ "n" }, "<Leader>ts", ":lua vim.treesitter.start()<CR>")
vim.keymap.set({ "n" }, "<Leader>tss", ":lua vim.treesitter.stop()<CR>")
vim.keymap.set("n", "<Leader>nc", function()
  vim.cmd.edit(vim.fn.expand("$HOME/.config/nvim/init.lua"))
  vim.cmd.lcd("%:p:h")
end)
